module.exports = {
  URL_VAGALUME: 'https://api.vagalume.com.br/search.php',
  Status: {
    FIRST_INPUT: 'FIRST_INPUT',
    MAIN_MENU: 'MAIN_MENU',
    WAIT_MUSIC_EX: 'WAIT_MUSIC_EX',
    WAIT_MUSIC_TITLE: 'WAIT_MUSIC_TITLE',
    WAIT_AUTHOR: 'WAIT_AUTHOR',
    WAIT_ARTIST_NAME: 'WAIT_ARTIST_NAME',
    WAIT_MUSIC_NAME: 'WAIT_MUSIC_NAME',
    WAIT_ARTIST_NAME_TYPE_SEARCH: 'WAIT_ARTIST_NAME_TYPE_SEARCH',

    SEARCH_MUSIC_BY_NAME: 'SEARCH_MUSIC_BY_NAME',
    SEARCH_MUSICS_BY_AUTHOR_NAME: 'SEARCH_MUSIC_BY_NAME'
  }
}

